### ISSUE TITLE
Is it allowed to backport this library to older minecraft versions and pr the backport back to this repository?

### ISSUE THREAD

**Issue by thecatcore** [TechnoVisionDev/ChemLib#2]
Asking because the readme states that unless explicitly said, this repository is All Right Reserved.

**Comment by TechnoVisionDev** [comment]
@Dark-Arcana will have to give his input as he owns the rights to ChemLib. I personally have no plans to backport.

**Comment by Dark-Arcana** [comment]
Porting is hard work. You have to basically rewrite (usually in a worse way when back porting) the entire mod. It's not something I ever plan on doing. But if you write a functional and mostly bug free backport and PR it into this repository, we can release it to CurseForge under the same project.

**Comment by thecatcore** [comment]
Ok, good to know, thanks.
